// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Session05.OOConfig;

namespace Session05.OOConfig.Migrations
{
    [DbContext(typeof(Session05Context))]
    [Migration("20210121083626_inheritance4")]
    partial class inheritance4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Session05.OOConfig.Inheritance.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Session05.OOConfig.Inheritance.Student", b =>
                {
                    b.HasBaseType("Session05.OOConfig.Inheritance.Person");

                    b.Property<string>("StudentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Session05.OOConfig.Inheritance.Teacher", b =>
                {
                    b.HasBaseType("Session05.OOConfig.Inheritance.Person");

                    b.Property<string>("TeacherNumber")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Session05.OOConfig.Inheritance.Student", b =>
                {
                    b.HasOne("Session05.OOConfig.Inheritance.Person", null)
                        .WithOne()
                        .HasForeignKey("Session05.OOConfig.Inheritance.Student", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Session05.OOConfig.Inheritance.Teacher", b =>
                {
                    b.HasOne("Session05.OOConfig.Inheritance.Person", null)
                        .WithOne()
                        .HasForeignKey("Session05.OOConfig.Inheritance.Teacher", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
