// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Session05.RelationConfiguration;

namespace Session05.RelationConfiguration.Migrations
{
    [DbContext(typeof(Session05Context))]
    [Migration("20210121064048_init-attr-child-set-fk")]
    partial class initattrchildsetfk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Session05.RelationConfiguration.Attibutes.ChildAttr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ParentIdFk")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentIdFk");

                    b.ToTable("ChildAttr");
                });

            modelBuilder.Entity("Session05.RelationConfiguration.Attibutes.ParentAttr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("ParentAttrs");
                });

            modelBuilder.Entity("Session05.RelationConfiguration.Attibutes.ChildAttr", b =>
                {
                    b.HasOne("Session05.RelationConfiguration.Attibutes.ParentAttr", "Parent")
                        .WithMany("ChildAttrs")
                        .HasForeignKey("ParentIdFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Session05.RelationConfiguration.Attibutes.ParentAttr", b =>
                {
                    b.Navigation("ChildAttrs");
                });
#pragma warning restore 612, 618
        }
    }
}
